// <auto-generated />
using System;
using Api.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Api.Models.Atleta", b =>
                {
                    b.Property<int>("AtletaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AtletaId"));

                    b.Property<string>("EmailAtleta")
                        .HasColumnType("longtext");

                    b.Property<string>("NomeAtleta")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroTelefone")
                        .HasColumnType("longtext");

                    b.Property<uint?>("PartidasGanhas")
                        .HasColumnType("int unsigned");

                    b.Property<int>("PartidasId")
                        .HasColumnType("int");

                    b.Property<uint?>("PartidasJogadas")
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("PartidasPerdidas")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Senha")
                        .HasColumnType("longtext");

                    b.HasKey("AtletaId");

                    b.ToTable("atletas");
                });

            modelBuilder.Entity("Api.Models.AtletasPartida", b =>
                {
                    b.Property<uint?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint?>("Id"));

                    b.HasKey("Id");

                    b.ToTable("atletasPartidas");
                });

            modelBuilder.Entity("Api.Models.Partidas", b =>
                {
                    b.Property<int>("PartidasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PartidasId"));

                    b.Property<int?>("AtletaId")
                        .HasColumnType("int");

                    b.Property<uint?>("Games")
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("PartidasGamesId")
                        .HasColumnType("int unsigned");

                    b.Property<Guid>("PartidasIdGuid")
                        .HasColumnType("char(36)");

                    b.Property<string>("SenhaPartida")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("PartidasId");

                    b.HasIndex("AtletaId");

                    b.ToTable("partidas");
                });

            modelBuilder.Entity("Api.Models.PartidasGames", b =>
                {
                    b.Property<uint?>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint?>("id"));

                    b.Property<int?>("PartidasId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("PartidasId");

                    b.ToTable("partidasGames");
                });

            modelBuilder.Entity("Api.Models.Ranking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("ranking");
                });

            modelBuilder.Entity("Api.Models.Partidas", b =>
                {
                    b.HasOne("Api.Models.Atleta", null)
                        .WithMany("Partidas")
                        .HasForeignKey("AtletaId");
                });

            modelBuilder.Entity("Api.Models.PartidasGames", b =>
                {
                    b.HasOne("Api.Models.Partidas", null)
                        .WithMany("PartidasGames")
                        .HasForeignKey("PartidasId");
                });

            modelBuilder.Entity("Api.Models.Atleta", b =>
                {
                    b.Navigation("Partidas");
                });

            modelBuilder.Entity("Api.Models.Partidas", b =>
                {
                    b.Navigation("PartidasGames");
                });
#pragma warning restore 612, 618
        }
    }
}
